import React,{ Component, img} from 'react';
import {Table, Container} from "react-materialize"
import "./SearchByIngredient.css"



class IconContainer extends Component {
  

  render() {
 
    return (
      <div>
          <Container>
          <Table>
              <tbody>
                    <tr>
                        <td>
                        <img className="apple"
                            src={require("./Images/apple.png")}
                            alt="apple"
                            onClick={this.props.addIngredientImg}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/asparagus.png")}
                            alt="asparagus"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/banana.png")}
                            alt="banana"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/beer.png")}
                            alt="beer"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/bread.png")}
                            alt="bread"
                            onClick={this.props.handleClick}
                            />
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <img
                            src={require("./Images/broccoli.png")}
                            alt="broccoli"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/burger.png")}
                            alt="burger"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/carrot.png")}
                            alt="carrot"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/cheese.png")}
                            alt="cheese"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/cherry.png")}
                            alt="cherry"
                            onClick={this.props.handleClick}
                            />
                        </td>
                    </tr>
                    <tr>
                    <td>
                        <img
                            src={require("./Images/chicken.png")}
                            alt="chicken"
                            onClick={this.props.handleClick}
                            />
                        </td>  
                        <td>
                        <img
                            src={require("./Images/chili.png")}
                            alt="chili"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/coffee.png")}
                            alt="coffee"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/crab.png")}
                            alt="crab"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/cucumber.png")}
                            alt="cucumber"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                    </tr>
                    <tr>
                    <td>
                        <img
                            src={require("./Images/donut.png")}
                            alt="donut"
                            onClick={this.props.handleClick}
                            />
                        </td>
                        <td>
                        <img
                            src={require("./Images/egg.png")}
                            alt="egg"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/fish.png")}
                            alt="fish"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/fries.png")}
                            alt="fries"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/garlic.png")}
                            alt="garlic"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                    </tr>
                    <tr>
                    <td>
                        <img
                            src={require("./Images/grapes.png")}
                            alt="grapes"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/hotdog.png")}
                            alt="hotdog"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/kiwi.png")}
                            alt="kiwi"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/lemon.png")}
                            alt="lemon"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/lime.png")}
                            alt="lime"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                    </tr>
                    <tr>
                    <td>
                        <img
                            src={require("./Images/mango.png")}
                            alt="mango"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/milk.jpg")}
                            alt="milk"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/mushroom.png")}
                            alt="mushroom"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/onion.png")}
                            alt="onion"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/orange.png")}
                            alt="orange"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                    </tr>
                    <tr>
                    <td>
                        <img
                            src={require("./Images/pizza.png")}
                            alt="pizza"
                            onClick={this.props.handleClick}
                            />
                        </td> <td>
                        <img
                            src={require("./Images/pumpkin.png")}
                            alt="pumpkin"
                            onClick={this.props.handleClick}
                            />
                        </td> <td>
                        <img
                            src={require("./Images/sandwiches.png")}
                            alt="sandwiches"
                            onClick={this.props.handleClick}
                            />
                        </td> <td>
                        <img
                            src={require("./Images/sausages.png")}
                            alt="sausages"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/shrimp.png")}
                            alt="shrimp"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                    </tr>
                    <tr>
                    <td>
                        <img
                            src={require("./Images/steak.png")}
                            alt="steak"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/strawberry.png")}
                            alt="strawberry"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/tomato.png")}
                            alt="tomato"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/watermelon.png")}
                            alt="watermelon"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                        <td>
                        <img
                            src={require("./Images/mango.png")}
                            alt="mango"
                            onClick={this.props.handleClick}
                            />
                        </td> 
                    </tr>
                </tbody>
            </Table>
           </Container>
      </div>
    )
  }
}

export default IconContainer;